receivers:
  otlp:
    protocols:
      http:
        endpoint: ${OTLP_RECEIVER_HTTP_ENDPOINT:-0.0.0.0:4317}

exporters:
  otlp/tempo:
    endpoint: ${TEMPO_EXPORTER_ENDPOINT:-tempo:4317}
    tls:
      insecure: true

  otlphttp/loki:
    endpoint: ${LOKI_EXPORTER_ENDPOINT:-http://loki:3100/otlp}
    tls:
      insecure: true

  prometheus:
     endpoint: ${PROMETHEUS_EXPORTER_ENDPOINT:-0.0.0.0:9090}

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/tempo]

    logs:
      receivers: [otlp]
      exporters: [otlphttp/loki]

    metrics:
      receivers: [otlp]
      exporters: [prometheus]
